[package]
name = "slang_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
slang_core = { path = "../core" }
serde_yaml = "0.9.16"
notify = "4.0.17"
clap = { version = "4.1.4", features = ["derive"] }
serde_json = "1.0.93"
